---
title: "STAR Model"
output: html_notebook
---

```{r}
library(tscount)
library(urca)
library(tseries)
library(factoextra)
library(vars)
library(BigVAR)
library(BBmisc)
library(dtw)
library(TSclust)
library(dtwclust)
library(rTensor)
library(tensorA)
library(amap)
library(gstar)
set.seed(1234)

#Load dataset
full_df <- read.csv("/home/angps/Documents/Thesis/Data/full_df_with_exo.csv")
df_atleast_50cts <- read.csv("/home/angps/Documents/Thesis/Data/df_>=50_with_exo.csv")
df_atleast_50cts_endo <- read.csv("/home/angps/Documents/Thesis/Data/data_>=50cts.csv")
loc_df <- read.csv("/home/angps/Documents/Thesis/Data/location_map.csv")

# index where locations have at least 50 non-zero counts
index_loc_atleast50 <- c(19,  23,  38,  43,  44,  53,  58,  62,  79,  89,  90,  93,  98,
            105, 109, 111, 123, 141, 155, 159, 162, 163, 233, 241, 243, 301,
            368, 397, 413, 441, 511, 559, 577, 680, 684, 688, 696, 707, 732,
            753, 777, 795)  
mini_loc_df <- loc_df[index_loc_atleast50,]
# Split to training/testing
train_small <- df_atleast_50cts_endo[,1:198]
test_small <- df_atleast_50cts_endo[,199:204]
train_full <- full_df[1:839,1:198]
test_full <- full_df[1:839,199:204]
```

```{r}
# Function to convert df to tensor
convert_df_to_tensor = function(df) {
    row <- dim(df)[1]
    col <- dim(df)[2]
    tensor <- rand_tensor(modes = c(row,col,1))
    for (i in c(1:row)) {
        for (j in c(1:col)) {
            tensor@data[i,j,1] = df[i,j]
        }
    }
    return(tensor)
}

replace_values = function(df, rec_tensor) {
    row <- dim(df)[1]
    col <- dim(df)[2]
    for (i in c(1:row)) {
        for (j in c(1:col)) {
            if (df[i,j]==0) {
                df[i,j] = rec_tensor@data[i,j,1]
            }
        }
    }
    return(df)
}

tensor <- convert_df_to_tensor(train_full)
tucker_tensor <- tucker(tensor, ranks=c(50,50,1))
recovered_tensor <- ttl(tucker_tensor$Z, tucker_tensor$U,1:3)
fnorm_score <- fnorm(tensor - recovered_tensor) / fnorm(tensor)
```

# Replace original 0s with new recovered values
```{r}
rec_df = replace_values(train_full, recovered_tensor)
write.csv(rec_df, "/home/angps/Documents/Thesis/Data/recovered_df.csv", row.names = FALSE)
```


