---
title: "VAR Model"
output: html_notebook
---

```{r}
library(urca)
library(BigVAR)
library(tseries)
```

```{r}
# Load dataset
full_df <- read.csv("/home/angps/Documents/Thesis/Data/data.csv")
df_atleast_50cts <- read.csv("/home/angps/Documents/Thesis/Data/data_>=50cts.csv")
```

```{r}
df_t_small_df <- t(df_atleast_50cts)
colnames(df_t_small_df) = c(1:42)

df_t_full_df <- t(full_df)
colnames(df_t_full_df) = c(1:839)
```

```{r}
# Test stationrity of all locations and return how many locations with stationary time series
stationary_test_all_loc = function(df) {
    num_locs = dim(df)[2]  # number of locations
    stationary_ct <- 0
    for (i in c(1 : num_locs)) {  # For each location
        adf_result <- suppressWarnings(adf.test(df[1:198, i]))  # Apply adf test first 198 values as training set has 198 values
        p_val <- adf_result$p.value  # get p_value of adf test
        if (p_val <= 0.05 || is.nan(p_val)) {  # If stationary
            stationary_ct = stationary_ct + 1
        }
    }
    print(paste0("Number of stationary locations/Total Locations: ", stationary_ct, " / " , num_locs))
}

fit_and_eval_var = function(diff_df, ori_df, p, struct, T1, T2) {
    "
    Fit and evaluate using VAR model. (assuming VAR applied on differenced series)
    Inputs: 
        diff_df: dataset after performing differencing level of 1
        ori_df: Original dataset
        p: Maximum lag order
        struct: Choice of penalty structure
        T1: Index of time series in which to start cross validation
        T2: Index of times series in which to start forecast evaluation
    "
    model = constructModel(diff_df, p = p, struct = struct, gran = c(25,10), T1 = T1, T2 = T2)
    var_model <- cv.BigVAR(model)  # Fit VAR Model
    prev_pred <- ori_df[,198]  # Get value at timestep 198 
    pred <- c()
    errors <- 0
    error_arr <- c()
    fitted_val <- c()
    for (i in c(1:6)) {  # For each timestep
        diff <- var_model@fitted[dim(var_model@fitted)[1] - (6-i),]  # Get predicted difference
        curr_pred <- prev_pred + diff  # COnvert to original values
        act <- ori_df[, 198 + i]
        error_arr <- c(error_arr, c(curr_pred - act))  # Calculate residuals
        fitted_val <- c(fitted_val, curr_pred)
        error <- sum((curr_pred - act) ^ 2)
        errors <- errors + error
        prev_pred <- curr_pred
    }
    return (list("Errors_array" = error_arr, "VAR_Errors" = var_model@resids, "Fitted_Values" = fitted_val, "VAR_Fitted" = var_model@fitted, "MSE" = errors/6))
}

```

# Apply VAR on smaller dataset 

```{r}
stationary_test_all_loc(df_t_small_df)
```

```{r}
## DIFFERENCING ##
diff_small_df <- diff(df_t_small_df, differences=1)
stationary_test_all_loc(diff_small_df)
```

```{r}
# Fit and evaluate VAR on small dataset
result <- fit_and_eval_var(diff_small_df, df_atleast_50cts, struct = "Basic", p = 6, T1 = 156, T2 = 198)
error_arr <- result$Errors_array
var_error <- result$VAR_Errors
var_fitted <- result$VAR_Fitted
MSE <- result$MSE
fitted_val <- result$Fitted_Values
print(paste0("MSE of fitting VAR on small dataset: ", MSE))
```




# Apply VAR on full dataset 

```{r}
stationary_test_all_loc(df_t_full_df)
```

```{r}
## DIFFERENCING ##
diff_full_df <- diff(df_t_full_df, differences=1)
stationary_test_all_loc(diff_full_df)
```

```{r}
# Fit and evaluate VAR on full dataset
result <- fit_and_eval_var(diff_full_df, full_df, struct = "Basic", p = 6, T1 = 156, T2 = 198)
error_arr <- result$Errors_array
var_error <- result$VAR_Errors
var_fitted <- result$VAR_Fitted
MSE <- result$MSE
fitted_val <- result$Fitted_Values
print(paste0("MSE of fitting VAR on small dataset: ", MSE))
```

```{r}
par(mfrow=c(2,2))
plot(as.vector(var_error), main="Residuals plot of VAR model", 
  xlab="Index", ylab="Residuals")
hist(as.vector(var_error), main = "Historgram of residuals")
qqnorm(as.vector(var_error))
qqline(as.vector(var_error))
#dev.copy(jpeg,filename="/home/angps/Documents/Thesis/Report/Images/Full_VAR_diff_resids.jpg");
#dev.off ();
```

```{r}
plot(as.vector(var_fitted),as.vector(var_error), main="Plot of residuals against fitted values", 
  xlab="Fitted Values", ylab="Residuals")
#dev.copy(jpeg,filename="/home/angps/Documents/Thesis/Report/Images/Full_VAR_diff_resids_vs_values.jpg");
#dev.off ();
```


