---
title: "Clustering"
output: html_notebook
---

```{r}
library(tscount)
library(urca)
library(factoextra)
library(vars)
library(BigVAR)
library(BBmisc)
library(amap)
set.seed(1234)
```

```{r}
#Load dataset
full_df <- read.csv("/home/angps/Documents/Thesis/Data/full_df_with_exo.csv")
df_atleast_50cts <- read.csv("/home/angps/Documents/Thesis/Data/df_>=50_with_exo.csv")
df_atleast_50cts_endo <- read.csv("/home/angps/Documents/Thesis/Data/data_>=50cts.csv")
loc_df <- read.csv("/home/angps/Documents/Thesis/Data/location_map.csv")
index_loc_atleast42 <- c(19,  23,  38,  43,  44,  53,  58,  62,  79,  89,  90,  93,  98,
            105, 109, 111, 123, 141, 155, 159, 162, 163, 233, 241, 243, 301,
            368, 397, 413, 441, 511, 559, 577, 680, 684, 688, 696, 707, 732,
            753, 777, 795)
mini_loc_df <- loc_df[index_loc_atleast42,]
train <- df_atleast_50cts_endo[,1:198]
test <- df_atleast_50cts_endo[,199:204]
```

```{r}
rownames(mini_loc_df) <- mini_loc_df$location
```

```{r}
## CLUSTERING BY LOCATION
fviz_nbclust(mini_loc_df, kmeans, method = "wss", k.max = 24) + theme_minimal() + ggtitle("the Elbow Method")

```

```{r}
### Perform Clustering on locations ####
num_clusters <- 3
km <- kmeans(mini_loc_df[,c(2:3)], centers = num_clusters)

str(km)
```

```{r}
assign_cluster_by_loc = function(loc_df, ori_df, num_clust) {
    "
    Cluster by geographical locations, aggregate the locations into clusters by summing up all locations' demand in the respective cluster
    "
    km <- kmeans(loc_df[,c(2:3)], centers = num_clust)  #Cluster using latitude and longitude
    clusters <- list()
    df_cols <- list()
    for (i in c(1 : num_clust)) {
        clust <- which(km$cluster %in% c(i))
        clusters[[i]] <- clust
        cluster_orders <- colSums(ori_df[clust,])
        df_cols[[i]] <- cluster_orders
    } 
    cluster_df <- data.frame(df_cols)
    return (list("cluster_df" = cluster_df, "cluster_ind" = clusters))
}
result<-assign_cluster_by_loc(mini_loc_df, df_atleast_50cts_endo,3)
```



```{r}
#### Allocate locs to cluster ###
cluster_1 <- which(km$cluster %in% c(1))
cluster_2 <- which(km$cluster %in% c(2))
cluster_3 <- which(km$cluster %in% c(3))

clusters <- list()
clusters[[1]] <- cluster_1
clusters[[2]] <- cluster_2
clusters[[3]] <- cluster_3


#### Combine clusters orders into datafrmae ###
cluster_1_orders <- colSums(df_atleast_50cts_endo[cluster_1,])
cluster_2_orders <- colSums(df_atleast_50cts_endo[cluster_2,])
cluster_3_orders <- colSums(df_atleast_50cts_endo[cluster_3,])

cluster_df <- data.frame(list(cluster_1_orders, cluster_2_orders, cluster_3_orders))
```

```{r}
#### Test for stationarity  ###
stationary_test = ca.jo(cluster_df, type="trace", K=6, ecdet="none", spec="longrun")
summary(stationary_test)
```

```{r}
#### Train VAR model on it  ###
Y = data.matrix(result$cluster_df)
model = constructModel(Y, p = 6, struct = "Basic", gran = c(50,25), T1 = 156, T2 = 198)
#model = constructModel(Y, p = 9, struct = "Basic", gran = c(25,10), T1 = 100, T2 = 200)
var_model <- cv.BigVAR(model)
```


```{r}
# Predict Cluster demand 
cluster_pred <- tail(var_model@fitted,6)
```

```{r}
# Function to assign demand to location
assign_clust_demand = function(clust_pred){
  num_clust <- dim(clust_pred)[2]
  pred <- matrix(0, nrow = 6, ncol = 42)  
  for (i in c(1:num_clust)) {
      clust_ind <- result$cluster_ind[[i]]  
      clust_order_by_loc <- rowSums(train[clust_ind,])
      for (j in c(1:length(clust_ind))) {
          loc_prop <- clust_order_by_loc[j]/sum(clust_order_by_loc)
          for (t in c(1:6)) {
              clust_total_order <- clust_pred[t, i]
              ind <- clust_ind[j]
              pred[t, ind] <- loc_prop * clust_total_order
          }
      }
  }
  return (pred) 
}


# Assign demand to locations

pred <- assign_clust_demand(cluster_pred)

```

```{r}
# calculate error
errors <- 0
error_arr <- c()
fitted_val <- c()
for (i in c(1:6)) {
    curr_pred <- pred[i, 1:42]
    act <- df_atleast_50cts_endo[,198 + i]
    error_arr <- c(error_arr, c(curr_pred - act))
    fitted_val <- c(fitted_val, curr_pred)
    error <- sum((curr_pred - act) ^ 2)
    errors <- errors + error
    prev_pred <- curr_pred
}

print(paste0(" MSFE: ", errors/6))
```






