---
title: "GLM Model on full dataset"
output: html_notebook
---

```{r}
library(tscount)
library(urca)
```

```{r}
#Load dataset
full_df <- read.csv("/home/angps/Documents/Thesis/Data/df_>=1cts.csv")
df_atleast_50cts <- read.csv("/home/angps/Documents/Thesis/Data/data_>=50cts.csv")
```

```{r}
train <- full_df[,1:162]
test <- full_df[,163:204]
#for (obs in c(6,12,18)) {
  #for (m in c(6, 12, 18, 24)) {
for (obs in c(1)) {
   for (m in c(1)) {
      errors <- 0
      for (i in c(1:dim(train)[1])) {
          fit <- suppressWarnings(tsglm(as.numeric(train[i,]), model = list(past_obs =  c(1:obs), past_mean = m), distr = "poisson"))
          pred <- predict(fit, n.ahead=42, global=TRUE)
          error <- sum(((as.numeric(test[i,]) - pred$pred)) ^ 2)
          errors <- errors + error
      }
      print(paste0("Max Past ObsL ", obs ," Past Mean: ", m, " MSFE: ", errors/42))
  }
}

```

```{r}
plot(error_arr, main="Residuals plot of GLM model", 
  xlab="Index", ylab="Residuals")
dev.copy(jpeg,filename="/home/angps/Documents/Thesis/Report/Images/Full_GLM_resids.jpg");
dev.off ();

```

```{r}
plot(fitted_val, error_arr, main="Plot of residuals against fitted values", 
  xlab="Fitted values", ylab="Residuals")
dev.copy(jpeg,filename="/home/angps/Documents/Thesis/Report/Images/Full_GLM_resids_vs_fitted.jpg");
dev.off ();

```


```{r}
acf(error_arr, main="ACF plots of residuals")
dev.copy(jpeg,filename="/home/angps/Documents/Thesis/Report/Images/Full_GLM_acf.jpg");
dev.off ();
```

```{r}
summary(fit)
```



