---
title: "STAR Model"
output: html_notebook
---

```{r}
# Load libraries
library(tscount)
library(urca)
library(philentropy)
library(gstar)
# Load dataset
df_atleast_50cts <- read.csv("/home/angps/Documents/Thesis/Data/data_>=50cts.csv")
full_df <- read.csv("/home/angps/Documents/Thesis/Data/df_>=1cts.csv")

# TRAIN TEST SPLIT:  Use 198 training data and 6 training data
# Transform dataset to periods as rows and locs as columns
train_small_df <- t(df_atleast_50cts[,1:198])
test_small_df <- t(df_atleast_50cts[,199:204])
train_full_df <- t(full_df[,1:198])
test_full_df <- t(full_df[,199:204])
```

# Implement function to fit and evaluate GLM
```{r}

fit_and_evaluate_star = function(train, test, ar_term, ma_term){
    # Small subset
    num_per_train = dim(train)[1]
    num_loc_train = dim(train)[2]
    
    # set uniform weights
    weight <- diag(-1, num_loc_train, num_loc_train) + matrix(1, num_loc_train, num_loc_train)
    weight = weight/(num_loc_train)
    
    # Fit STARMA models
    fit <- gstar(train, weight = weight,
    p = ar_term, d = ma_term, est = "OLS")
    
    # Predict and get error metrics
    errors <- 0
    quad_score <- 0
    
    # predict 6 step ahead
    pred <- predict(fit, n = dim(test)[1])
    error <- sum(((c(test) - c(pred))) ^ 2)
    errors <- errors + error
    for (i in c(1:dim(test)[1])) {
        for (j in c(1:num_loc_train)) {
            if (isFALSE(is.nan(scoring(test[i,j], pred[i,j], distr=c("poisson"))['quadratic']))) {
                quad_score <- quad_score + scoring(test[i,j], pred[i,j], distr=c("poisson"))['quadratic']
            }
        }
    }
    return (list("MSE" = errors/6, 'Quadratic(Brier) Score' = quad_score/6))
}

```


# Apply it on the subset of the dataset 
```{r}
# Fit and evaluate on smaller subset of dataset
result = fit_and_evaluate_star(train_small_df, test_small_df, ar_term=5, ma_term=0)
MSE = result$MSE
quad_score = result$`Quadratic(Brier) Score`

print(paste0("MSE of fitting STAR on smaller subset of dataset: ", MSE))
print(paste0("Quadratic Score of fitting STAR on smaller subset of dataset: ", quad_score))
```

# Apply it on the full of the dataset 
```{r}
# Fit and evaluate on full dataset
result = fit_and_evaluate_star(train_full_df, test_full_df, ar_term=1, ma_term=0)
MSE = result$MSE
quad_score = result$`Quadratic(Brier) Score`

print(paste0("MSE of fitting STAR on full dataset: ", MSE))
print(paste0("Quadratic Score of fitting STAR on full dataset: ", quad_score))
```



